### PR TITLE
Functionality of editing a part not in your namespace is now fixed. 

### PR DESCRIPTION
**Pull request by SamuelSauce**

### CODE REVIEW

**Comment by cjmyers** [comment]
I'm still not getting a namespace update request for Add Scars.

**Comment by cjmyers** [comment]
It is also still asking for a namespace change when I click on a part for editing. It should only ask this question when I'm click save.  Right now it happens both when you click on the part to edit it AND when you save.

**Comment by SamuelSauce** [comment]
Are you sure that you got my latest commit? This behavior is not happening
on my machine.

**Comment by cjmyers** [comment]
Oops I will need to double check that.

**Comment by cjmyers** [comment]
That was the problem.  It seems to be working.  I will poke on it more to be sure.

**Comment by cjmyers** [comment]
Ok, getting very close now.  Seems to work for add, delete, edit.  However, adding scars does not seem to update the namespace.

**Comment by SamuelSauce** [comment]
Flipping orientation should now work again, I just pushed. I didn't have
any problems with adding a scar though, it updates the namespace for me.
Additionally how do you mean by replacing a part from the registry?

**Comment by cjmyers** [comment]
When I say add scars, I mean by clicking on the add scars icon on top near the zoom in button.  Is that what you did?

As for replacing a part from registry, use pencil then import registry part.  Then, click edit one of the parts in your canvas, and click import registry part.  

Flip orientation is now working.

**Comment by SamuelSauce** [comment]
Oh I see what you mean for the add scars, i’ll take a look at that. I’ll
also take a look at replacing a part from registry.

**Comment by SamuelSauce** [comment]
Just pushed the adding scar fix. I'm confused as to how you would like the
importing a part from registry to work if the top level part is not in
namespace. Should the top level take the namespace of the newly imported
part? Or do you want the top level to take on the users namespace, and then
have the newly imported part stay in its own namespace?

**Comment by SamuelSauce** [comment]
That appears to be the behavior that I'm observing currently. My process
is: I import a part from cello, and then I am clicking to edit the
promoter. I then import a new promoter from registry. After, the new
promoter namespace is from what I just imported, with the top level being
now in my namespace. Let me know if there is a difference in what you are
seeing, and what is happening.

**Comment by cjmyers** [comment]
Cool.  Scars are working and importing part is working.  I think this may finally be sorted.

**Comment by cjmyers** [comment]
Fixes #330

**Pull request merged**
