### PR TITLE
So term changed.

### PR DESCRIPTION
**Pull request by SamuelSauce**

### CODE REVIEW

**Comment by cjmyers** [comment]
Looks good.  One minor problem though is both Operator sites still show up in the main role list when you edit the part.  Parts not in the pallet should also not appear in that list.

Toyed with the idea of changing it to Binding Site, but abbreviation of "BS" is not great :-)

**Comment by cjmyers** [comment]
This PR relates to issue #338

**Comment by SamuelSauce** [comment]
Just made a change to where it shouldn't appear in role selection. Let me
know if this is the behavior you wanted.

**Comment by cjmyers** [comment]
Pretty close.  The only issue I see now is that if you have the SO term Operator selected, it should still show Operator selected in the list.  To see, this, select No Glyph Assigned, then do role refinement of Operator.  This should show up as Operator now when you edit the glyph.  With no role refinements possible.  

Hmm, I now see that this is confusing.  Maybe we should actually have kept them both in the list but with different names, the one with SO term Binding Site, should show the cup with BS (Binding Site), and the original one should be Op (Operator).  The BS one should be the one in the pallet.

**Comment by SamuelSauce** [comment]
Just changed the SO term to 'Bind'. I think this was the behavior we decided on during meeting. Let me know if otherwise.

**Pull request merged**
